name = "scheme-properties"
version = "0.1.0"
defaultTargets = ["SchemeProperties", "SchemePropertiesTest", "SchemePropertiesExamples"]

[leanOptions]
autoImplicit = false
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
weak.linter.style.header = false

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "83abb3e776bdefcbc447a1e44d0debe4010039e5"

[[require]]
name = "coherent-modules"
git = "https://github.com/FormalFrontier/coherent-modules.git"
rev = "408a52bd54df17ccc928ce970942f1313ff10d5c"

[[require]]
name = "finiteEtaleAlgebras"
git = "https://github.com/FormalFrontier/finite-etale-algebras.git"
rev = "79575f65c9edec560f27756917761eed78331a2a"

[[require]]
name = "multivariate-polynomials"
git = "https://github.com/FormalFrontier/multivariate-polynomials.git"
rev = "0a93db475d7a36434c3926f604b638f0d58f8142"

[[lean_lib]]
name = "SchemeProperties"

[[lean_lib]]
name = "SchemePropertiesTest"
globs = ["Test.+"]

[[lean_lib]]
name = "SchemePropertiesExamples"
globs = ["Examples.+", "SchemePropertiesExamples.+"]
