/-
SPDX-License-Identifier: Apache-2.0
Authors: Formal Frontier Agents
-/
module

public import Mathlib.RingTheory.Polynomial.Quotient
public import Mathlib.RingTheory.Spectrum.Prime.Topology

@[expose] public section

set_option warningAsError true

/-!
# Evaluation primes of a polynomial ring

Evaluation at a point of an integral domain determines a prime of its polynomial
ring. Its kernel is also the principal ideal generated by `X - C x`.

## References

* Mathlib's polynomial evaluation kernel and quotient-by-`X - C x` equivalence.
-/

namespace Polynomial

universe u

variable {R : Type u} [CommRing R] [IsDomain R]

/-- The prime ideal of polynomials vanishing at `x`. -/
noncomputable def evalPrime (x : R) : PrimeSpectrum R[X] :=
  ⟨RingHom.ker (evalRingHom x), RingHom.ker_isPrime (evalRingHom x)⟩

@[simp]
theorem evalPrime_asIdeal (x : R) : (evalPrime x).asIdeal = RingHom.ker (evalRingHom x) :=
  rfl

@[simp]
theorem mem_evalPrime_iff (x : R) (p : R[X]) :
    p ∈ (evalPrime x).asIdeal ↔ p.eval x = 0 := by
  simp [evalPrime, RingHom.mem_ker]

/-- The vanishing ideal at `x` is generated by `X - C x`. -/
theorem evalPrime_asIdeal_eq_span (x : R) :
    (evalPrime x).asIdeal = Ideal.span {X - C x} := by
  rw [evalPrime_asIdeal, ker_evalRingHom]

@[simp]
theorem X_sub_C_mem_evalPrime_iff (x y : R) :
    X - C y ∈ (evalPrime x).asIdeal ↔ x = y := by
  rw [mem_evalPrime_iff]
  simp only [eval_sub, eval_X, eval_C, sub_eq_zero]

/-- Evaluation at distinct points gives distinct primes. -/
theorem evalPrime_injective : Function.Injective (evalPrime (R := R)) := by
  intro x y h
  have hmem : X - C x ∈ (evalPrime y).asIdeal := by
    rw [← h]
    simp
  exact ((X_sub_C_mem_evalPrime_iff y x).mp hmem).symm

end Polynomial
