module

import SchemeProperties.ComponentBaseChange

set_option warningAsError true

#print axioms AlgebraicGeometry.componentScalarExtensionAlgHom
#print axioms AlgebraicGeometry.baseChangedComponentSubalgebra
#print axioms AlgebraicGeometry.componentBaseChangeComparisonAlgHom
#print axioms AlgebraicGeometry.componentBaseChangeComparisonAlgHom_injective
#print axioms AlgebraicGeometry.componentBaseChangeComparison
#print axioms AlgebraicGeometry.toComponentScheme_comp_componentBaseChangeComparison
#print axioms AlgebraicGeometry.toConnectedComponentsSpec
#print axioms AlgebraicGeometry.toConnectedComponentsSpec_surjective
#print axioms AlgebraicGeometry.componentSubalgebra_finrank_eq_natCard_connectedComponents
#print axioms AlgebraicGeometry.natCard_connectedComponents_schemeBaseChange_eq_of_isSepClosed
#print axioms AlgebraicGeometry.componentSubalgebra_finrank_eq_natCard_separableClosure
#print axioms AlgebraicGeometry.natCard_connectedComponents_separableClosures_eq
#print axioms AlgebraicGeometry.componentBaseChangeComparisonAlgHom_surjective
#print axioms AlgebraicGeometry.baseChangedComponentSubalgebra_eq
#print axioms AlgebraicGeometry.componentBaseChangeComparisonAlgEquiv
#print axioms AlgebraicGeometry.componentBaseChangeIso
#print axioms AlgebraicGeometry.componentBaseChangeIso_hom
